/*
 * GIVEN TO YOU. Do not edit this file. You did not write it and you are not
 * being graded on it. Writing classes is January.
 *
 * AP-SUBSET-SCAN: SKIP
 *   This file overrides toString, which is outside the AP subset. It is here so
 *   that printing a Pet is convenient during the lab. You will never be asked to
 *   write or override toString.
 */
public class Pet {
    private String name;
    private int ageMonths;

    public Pet(String petName, int ageYears) {
        name = petName;
        ageMonths = ageYears * 12;
    }

    public Pet(String petName) {
        name = petName;
        ageMonths = 0;
    }

    public String getName() { return name; }
    public int getAgeMonths() { return ageMonths; }
    public void haveBirthday() { ageMonths += 12; }
    public String toString() { return name + " (" + ageMonths + " months)"; }
}
